=== lukasrynt/BI-XML/validation/countries.dtd
<!ELEMENT countries (country*)>

<!ELEMENT country (intro, chapter)>
<!ATTLIST country name #PCDATA>

<!ELEMENT intro (img+)>
<!ELEMENT img EMPTY>
<!ATTLIST img src CDATA #REQUIRED>

<!ELEMENT chapter (section*)>
<!ATTLIST chapter name CDATA #REQUIRED>

<!ELEMENT section (paragraph*|(#PCDATA)|subfield*|list*)>
<!ATTLIST section
        name CDATA #REQUIRED
        value CDATA #IMPLIED>

<!ELEMENT paragraph (#PCDATA)>

<!ELEMENT subfield (#PCDATA)>
<!ATTLIST subfield
        oneline (yes|no) "no"
        name CDATA #REQUIRED
        value CDATA #IMPLIED
        unit CDATA #IMPLIED>

<!ELEMENT list (item+)>

<!ELEMENT item (#PCDATA)>

=== lukasrynt/BI-XML/source/spain.xml
<!DOCTYPE countries SYSTEM "../validation/countries.dtd">
<countries>
    <author name="Lukas" surname="Rynt" email="ryntluka@fit.cvut.cz"/>
    <country name="Spain">
        <intro>
            <img src="https://www.cia.gov/library/publications/the-world-factbook/attachments/flags/SP-flag.jpg"/>
            <img src="https://www.cia.gov/library/publications/the-world-factbook/attachments/locator-maps/SP-locator-map.jpg"/>
            <img src="https://www.cia.gov/library/publications/the-world-factbook/attachments/maps/SP-map.jpg"/>
        </intro>
        <chapter name="Introduction">
            <section name="Background">
                <paragraph>
                    The United Kingdom has historically played a leading role in developing parliamentary democracy and in advancing literature and science. At its zenith in the 19th century, the British Empire stretched over one-fourth of the earth's surface. The first half of the 20th century saw the UK's strength seriously depleted in two world wars and the Irish Republic's withdrawal from the union. The second half witnessed the dismantling of the Empire and the UK rebuilding itself into a modern and prosperous European nation. As one of five permanent members of the UN Security Council and a founding member of NATO and the Commonwealth, the UK pursues a global approach to foreign policy. The Scottish Parliament, the National Assembly for Wales, and the Northern Ireland Assembly were established in 1998.
                </paragraph>
                <paragraph>
                    The UK has been an active member of the EU since its accession in 1973, although it chose to remain outside the Economic and Monetary Union. However, motivated in part by frustration at a remote bureaucracy in Brussels and massive migration into the country, UK citizens on 23 June 2016 narrowly voted to leave the EU. The UK is scheduled to depart the EU on 31 January 2020, but negotiations on the future EU-UK economic and security relationship will continue throughout 2020 and potentially beyond.
                </paragraph>
            </section>
        </chapter>
        <chapter name="Geography">
            <section name="Location">
                Western Europe, islands - including the northern one-sixth of the island of Ireland - between the North Atlantic Ocean and the North Sea; northwest of France
            </section>
            <section name="Geographic coordinates">
                54 00 N, 2 00 W
            </section>
            <section name="Map references" value="Europe"/>
            <section name="Area">
                <subfield oneline="yes" name="total" value="243,610" unit="sq km"/>
                <subfield oneline="yes" name="land" value="241,930" unit="sq km"/>
                <subfield oneline="yes" name="water" value="1,680" unit="sq km"/>
                <subfield name="note 1" oneline="yes" value="the percentage area breakdown of the four UK countries is: England 53%, Scotland 32%, Wales 9%, and Northern Ireland 6%"/>
                <subfield name="note 2" oneline="yes" value="includes Rockall and the Shetland Islands, which are part of Scotland"/>
                <subfield oneline="yes" name="country comparison to the world" value="81"/>
            </section>
            <section name="Area - comparative">
                <paragraph>twice the size of Pennsylvania; slightly smaller than Oregon</paragraph>
                <subfield name="Area comparison map">
                    <img src="https://www.cia.gov/library/publications/the-world-factbook/attachments/images/thumb/UK_area.jpg?1538604837"/>
                </subfield>
            </section>
            <section name="Land boundaries">
                <subfield oneline="yes" name="total" value="499" unit="km"/>
                <list name="border countries (1)">
                    <item name="Ireland" value="499" unit="km"/>
                </list>
            </section>
            <section name="Coastline">
                <data value="12,429" unit="km"/>
            </section>
            <section name="Maritime claims">
                <subfield name="territorial sea" value="12" unit="nm"/>
                <subfield name="continental shelf" value="as defined in continental shelf orders or in accordance with agreed upon boundaries"/>
                <subfield name="exclusive fishing zone" value="200" unit="nm"/>
            </section>
            <section name="Climate">
                <paragraph>temperate; moderated by prevailing southwest winds over the North Atlantic Current; more than one-half of the days are overcast</paragraph>
            </section>
            <section name="Terrain">
                <paragraph>mostly rugged hills and low mountains; level to rolling plains in east and southeast</paragraph>
            </section>
            <section name="Elevation">
                <subfield oneline="yes" name="mean elevation" value="162" unit="m"/>
                <subfield oneline="yes" name="lowest point" value="-4" unit="m" description="The Fens"/>
                <subfield oneline="yes" name="highest point" value="1,345" unit="m" description="Ben Nevis"/>
            </section>
            <section name="Natural resources">
                <list>
                    <item value="coal"/>
                    <item value="petroleum"/>
                    <item value="petroleum"/>
                    <item value="natural gas"/>
                    <item value="iron ore"/>
                    <item value="lead"/>
                    <item value="zinc"/>
                    <item value="gold"/>
                    <item value="tin"/>
                    <item value="limestone"/>
                    <item value="salt"/>
                    <item value="clay"/>
                    <item value="chalk"/>
                    <item value="gypsum"/>
                    <item value="potash"/>
                    <item value="silica sand"/>
                    <item value="slate"/>
                    <item value="arable land"/>
                </list>
            </section>
            <section name="Land use">
                <subfield oneline="yes" name="agricultural land" value="71" unit="%" year="2011 est."/>
                <subfield oneline="yes" name="arable land" value="25.11" unit="%" year="2011 est.">
                    <list>
                        <item name="permanent crops" value="0.2" unit="%" year="2011 est."/>
                        <item name="permanent pasture" value="45.7" unit="%" year="2011 est."/>
                    </list>
                </subfield>
                <subfield oneline="yes" name="forest" value="11.9" unit="%" year="2011 est."/>
                <subfield oneline="yes" name="other" value="17.1" year="2011 est."/>
            </section>
            <section name="Irrigated land">
                <data value="950" unit="sq km" year="2012"/>
            </section>
            <section name="Population distribution">
                the core of the population lies in and around London, with significant clusters found in central Britain around Manchester and Liverpool, in the Scotish lowlands between Endinburgh and Glasgow, southern Wales in and around Cardiff, and far eastern Northern Ireland centered on Belfast
            </section>
            <section name="Natural hazards">
                winter windstorms; floods
            </section>
            <section name="Environment - current issues">
                air pollution improved but remains a concern, particularly in the London region; soil pollution from pesticides and heavy metals; decline in marine and coastal habitats brought on by pressures from housing, tourism, and industry
            </section>
            <section name="Environment - international agreements">
                <list name="party to">
                    <item value="Air Pollution"/>
                    <item value="Air Pollution-Nitrogen Oxides"/>
                    <item value="Air Pollution-Persistent Organic Pollutants"/>
                    <item value="Air Pollution-Sulfur 94"/>
                    <item value="Air Pollution-Volatile Organic Compounds"/>
                    <item value="Antarctic-Environmental Protocol"/>
                    <item value="Antarctic-Marine Living Resources"/>
                    <item value="Antarctic Seals"/>
                    <item value="Antarctic Treaty"/>
                    <item value="Biodiversity"/>
                    <item value="Climate Change"/>
                    <item value="Climate Change-Kyoto Protocol"/>
                    <item value="Desertification"/>
                    <item value="Endangered Species"/>
                    <item value="Environmental Modification"/>
                    <item value="Hazardous Wastes"/>
                    <item value="Law of the Sea"/>
                    <item value="Marine Dumping"/>
                    <item value="Marine Life Conservation"/>
                    <item value="Ozone Layer Protection"/>
                    <item value="Ship Pollution"/>
                    <item value="Tropical Timber 83"/>
                    <item value="Tropical Timber 94"/>
                    <item value="Wetlands"/>
                    <item value="Whaling"/>
                </list>
                <subfield oneline="yes" name="singed, but not ratified" value="none of the selected agreements"/>
            </section>
            <section name="Geography - note">
                <paragraph>lies near vital North Atlantic sea lanes; only 35 km from France and linked by tunnel under the English Channel (the Channel Tunnel or Chunnel); because of heavily indented coastline, no location is more than 125 km from tidal waters</paragraph>
            </section>
        </chapter>
        <chapter name="People and Society">
            <section name="Population">
                <data value="65,761,117" year="July 2020 est."/>
